---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker://lpenz/omnilint:0.5.2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker/setup-buildx-action@v3.6.1
      - uses: docker/build-push-action@v6.6.1
