---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker://lpenz/omnilint:0.5.2
  publish-dockerhub:
    needs: [ omnilint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.14.0
      - uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.version.outputs.version_docker_ci != 'null'
      - uses: docker/build-push-action@v6.6.1
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}
